version: '{build}'
build_script:
- ps: ./Build.ps1 
test: off
artifacts:
- path: Serilog.Sinks.Elasticsearch*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: nvZ/z+pMS91b3kG4DgfES5AcmwwGoBYQxr9kp4XiJHj25SAlgdIxFx++1N0lFH2x
  on:
    branch: master